"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const category = [
      { name: "Art & Entertainment" },
      { name: "Characters", parent_category_id: 1 },
      { name: "Objects", parent_category_id: 1 },
      { name: "Environments", parent_category_id: 1 },
      { name: "Vehicles", parent_category_id: 1 },
      { name: "Animals", parent_category_id: 2 },
      { name: "People", parent_category_id: 2 },
      { name: "Mythical creatures", parent_category_id: 2 },
      { name: "Furniture", parent_category_id: 3 },
      { name: "Props", parent_category_id: 3 },
      { name: "Decorations", parent_category_id: 3 },
      { name: "Landscapes", parent_category_id: 4 },
      { name: "Buildings", parent_category_id: 4 },
      { name: "Interiors", parent_category_id: 4 },
      { name: "Cars", parent_category_id: 5 },
      { name: "Airplanes", parent_category_id: 5 },
      { name: "Spaceships", parent_category_id: 5 },
      { name: "Architecture & Engineering" },
      { name: "Buildings", parent_category_id: 16 },
      { name: "Furniture", parent_category_id: 16 },
      { name: "Products", parent_category_id: 16 },
      { name: "Mechanical parts", parent_category_id: 16 },
      { name: "Residential", parent_category_id: 17 },
      { name: "Commercial", parent_category_id: 17 },
      { name: "Industrial", parent_category_id: 17 },
      { name: "Chairs", parent_category_id: 18 },
      { name: "Tables", parent_category_id: 18 },
      { name: "Beds", parent_category_id: 18 },
      { name: "Electronics", parent_category_id: 19 },
      { name: "Appliances", parent_category_id: 19 },
      { name: "Tools", parent_category_id: 19 },
      { name: "Gears", parent_category_id: 20 },
      { name: "Pistons", parent_category_id: 20 },
      { name: "Valves", parent_category_id: 20 },
      { name: "Fashion & Design" },
      { name: "Clothing", parent_category_id: 28 },
      { name: "Jewelry", parent_category_id: 28 },
      { name: "Accessories", parent_category_id: 28 },
      { name: "Characters", parent_category_id: 28 },
      { name: "Shirts", parent_category_id: 29 },
      { name: "Dresses", parent_category_id: 29 },
      { name: "Shoes", parent_category_id: 29 },
      { name: "Rings", parent_category_id: 30 },
      { name: "Necklaces", parent_category_id: 30 },
      { name: "Earrings", parent_category_id: 30 },
      { name: "Bags", parent_category_id: 31 },
      { name: "Hats", parent_category_id: 31 },
      { name: "Watches", parent_category_id: 31 },
      { name: "Science & Education" },
      { name: "Anatomy models", parent_category_id: 36 },
      { name: "Scientific equipment", parent_category_id: 36 },
      { name: "Historical artifacts", parent_category_id: 36 },
      { name: "Educational models", parent_category_id: 36 },
      { name: "Human body", parent_category_id: 37 },
      { name: "Animals", parent_category_id: 37 },
      { name: "Plants", parent_category_id: 37 },
      { name: "Microscopes", parent_category_id: 38 },
      { name: "Telescopes", parent_category_id: 38 },
      { name: "Robots", parent_category_id: 38 },
      { name: "Buildings", parent_category_id: 39 },
      { name: "Tools", parent_category_id: 39 },
      { name: "Weapons", parent_category_id: 39 },
      { name: "Molecules", parent_category_id: 40 },
      { name: "Planets", parent_category_id: 40 },
      { name: "Ecosystems", parent_category_id: 40 },
      { name: "Gaming & VR" },
      { name: "Characters", parent_category_id: 44 },
      { name: "Environments", parent_category_id: 44 },
      { name: "Objects", parent_category_id: 44 },
      { name: "Vehicles", parent_category_id: 44 },
      { name: "Players", parent_category_id: 45 },
      { name: "Enemies", parent_category_id: 45 },
      { name: "NPCs", parent_category_id: 45 },
      { name: "Levels", parent_category_id: 46 },
      { name: "Worlds", parent_category_id: 46 },
      { name: "Landscapes", parent_category_id: 46 },
      { name: "Weapons", parent_category_id: 47 },
      { name: "Tools", parent_category_id: 47 },
      { name: "Props", parent_category_id: 47 },
      { name: "Cars", parent_category_id: 48 },
      { name: "Spaceships", parent_category_id: 48 },
      { name: "Airplanes", parent_category_id: 48 },
    ];

    await queryInterface.bulkInsert("category", category);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("category", null, {});
  },
};
